### PR TITLE
Adding react v15 support

### PR DESCRIPTION
**Pull request by jshthornton**
#79

### CODE REVIEW

**Comment by Pomax** [comment]
what does this do for people still on React 14 though? I'll happily merge in code that makes things work with the latest React, but we don't want to break people who can't switch to 15 for a while.

**Comment by jshthornton** [comment]
No changes, as it is uses an existing well established library.

**Comment by Pomax** [comment]
in that case in it goes, thanks for the fix!

**Comment by Pomax** [comment]
v4.8.0 pushed to npm

**Pull request merged**
