### PR TITLE
Support React 0.14

### PR DESCRIPTION
**Pull request by martijnrusschen**
This adds support for the new ReactDOM

### CODE REVIEW

**Comment by Pomax** [comment]
this is massively backward compat. breaking, and will have to be a new major version rather than a patch update

**Comment by stoeffel** [comment]
Is there something I can do to help getting this merged?

@martijnrusschen you should not update the version number in a PR. This should be done by the maintainer of this repo when he prepares a release.
@Pomax You could add this scripts to make publishing easier:
```json
```

**Comment by martijnrusschen** [comment]
Version number has been reverted. Not sure if this actually fixes all the issues now. @stoeffel Are you able to confirm this is the correct solution?

**Comment by stoeffel** [comment]
Tried it with your branch in our app and it worked. Thx.
But I think this repo could use some tests to ensure it works after a change.

**Comment by Pomax** [comment]
@stoeffel I actually greatly prefer having a PR that comes with the updated version if it's going to break everything, which is why I asked @martijnrusschen to change it. `npm` is just a convenience tool, and in this case I want that major version bump before the PR is merged in. I don't want this code to land as a plain commit, it needs to be explicit about the fact that this is where things broke 0.12 and 0.13 =)

@martijnrusschen can you please put that version back in?

**Comment by stoeffel** [comment]
>  I actually greatly prefer having a PR that comes with the updated version if it's going to break everything

Your choice.

**Comment by martijnrusschen** [comment]
Done

**Comment by Pomax** [comment]
ah, but of course, because it's a package.json change, and I had to put in a reversion, package.json needs a sync up. Can you rebase on the latest master? (probably worth `pick`ing the first and just `squash`ing the subsequent commits so it's a single commit PR again)

**Comment by martijnrusschen** [comment]
Should be able to merge it now

**Comment by Pomax** [comment]
yep, looks clean. Is it possible to squash into one commit? (if not, it should still be easy to roll back if absolutely necessary, a single commit's easier to track though)

**Comment by JoshBarr** [comment]
Great timing @martijnrusschen, I just picked up a project to migrate to React 0.14 and was about to patch this very useful library myself. Thanks for doing it :+1:

**Comment by martijnrusschen** [comment]
Not sure how this should be squased into 1 commit. Steps I need to follow?

**Comment by stoeffel** [comment]
@martijnrusschen see http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by Pomax** [comment]
@stoeffel's link is pretty spot on, although there is one small warning and that's the fact that this will *probably* open up `vi` or `vim`, in which "editing" and "save and quit" are about as unintuitive as possible:

- to edit text, you type "i", which switches the input mode so that you can type actual text. you can hit "esc" to get back to the main input mode.
- to save a file and quit after editing, you type ":wq", where ":" pops up vi/vim's command prompt, "w" means "write this back to file", and "q" means quit.

So if you get stuck on this, let me know and I can fork your PR, do the squashing for us, and then merge that in

**Comment by martijnrusschen** [comment]
I tried squasing the commits, but didn't get it right. Will try it again tomorrow, or you can do it if you're in a hurry.

**Comment by stoeffel** [comment]
@Pomax would be great if this gets merged soon. You could use https://github.com/tj/git-extras/blob/master/Commands.md#git-pr and squash and merge. No need to fork this PR.

**Comment by Pomax** [comment]
Hmm, oddly, that command seems to no longer exist on the page you're linking to.

**Comment by Pomax** [comment]
that will check out the pr (which is easy to do with the usual fetch + checkout), but will not let me squash it and the push it up as a PR that gets tracked through github. I'd be squashing, merging, and pushing to master through git, which prevents some handy github.com functions like one click reverts being available.

**Comment by stoeffel** [comment]
I rebased and created a new pr. Would be great if it got merged now.

**Comment by Pomax** [comment]
v4.0.1 on https://www.npmjs.com/package/react-onclickoutside

**Pull request closed without merging**
