### PR TITLE
fix excludeScrollbar not working for horizontal scroll bar

### PR DESCRIPTION
**Pull request by yormo**
exclude horizontal Scrollbar

### CODE REVIEW

**Comment by Pomax** [comment]
I'm a little confused: if this is a fix for the horizontal scrollbar, why does the code introduce a *height* check, which would incur a vertical scrollbar, if any?

**Comment by rafeememon** [comment]
@pomax, I think this is because a horizontal scroll bar would reduce the height of a page since it appears along the bottom.  The existing vertical scroll bar check is analogous in that it checks for a reduced width.

**Comment by yormo** [comment]
@Pomax When horizontal scrollbar appear, clientHeight will become smaller, Through ‘clientY’ to check whether the event on horizontal scrollbar, This method is similar to your check vertical scrollbar.

**Comment by Pomax** [comment]
I see. Would you be willing to write a mocha test (./test/test.js) to verify this is doing the right thing?

**Pull request merged**
