### PR TITLE
Update react & react-dom peer-dep to support 17.x

### PR DESCRIPTION
**Pull request by h3rmanj**
Addresses #346

### CODE REVIEW

**Comment by Pomax** [comment]
Unfortunately, this alone is not enough to make things work. The CI task is currently failing on uglify, but I'm sure there are more deps that need to be checked before this will pass.

**Review by Pomax — CHANGES_REQUESTED** [review]
CI does not pass with just these updates.

**Comment by h3rmanj** [comment]
The latest release 6.7.1 failed for the same reason, i'm guessing there is some old build pipeline here?
This PR is only to fix the issue of not being able to install this package at all if you have npm v7, and react v17.

**Comment by h3rmanj** [comment]
The `warnings` flag is a top-level flag to uglify, so I moved it out of the `compress` options. Seems to have fixed the pipeline.
It's [`false` by default](https://github.com/mishoo/UglifyJS#minify-options) though, but i left it there for good measure.

**Comment by Pomax** [comment]
cheers. I'll merge this in and push a minor update.

**Comment by Pomax** [comment]
v6.10.0 published

**Pull request merged**
