### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by emmahsax**
Create MIT license file.

### CODE REVIEW

**Review by Pomax — CHANGES_REQUESTED** [review]
If you can rename this to just `LICENSE` instead of `LICENSE.txt`, should be good to go.

**Comment by emmahsax** [comment]
@Pomax Renamed!

**Comment by emmahsax** [comment]
@Pomax Any updates on this?

**Review by Pomax — APPROVED** [review]

**Comment by Pomax** [comment]
in it goes

**Pull request merged**
