### PR TITLE
353 typescript bug.

### PR DESCRIPTION
**Pull request by OscarBakker**

### CODE REVIEW

**Comment by Pomax** [comment]
If this fixes a genuine issue I'll all for it, but you kind of need to at least write a short explanation of why you filed this PR?

**Comment by OscarBakker** [comment]
> If this fixes a genuine issue I'll all for it, but you kind of need to at least write a short explanation of why you filed this PR?

True! I was using ViteJS for a typescript react project. When starting the project I instantly got an error. I think due to the on demand compilation which was going on with ViteJS, the file which included react-onclickoutside could'nt compile when I was actually starting the app in the browser.

**Comment by OscarBakker** [comment]
Is the problem clear?

**Comment by Pomax** [comment]
Yep. Does this pass `npm test`?

**Comment by OscarBakker** [comment]
> Yep. Does this pass `npm test`?

yes it does.

**Comment by OscarBakker** [comment]
can you merge it?

**Review by Pomax — APPROVED** [review]

**Comment by Pomax** [comment]
yep

**Comment by Pomax** [comment]
6.11 published

**Pull request merged**
