### PR TITLE
Fixes regression of #88

### PR DESCRIPTION
**Pull request by RichGuk**
I think #114 introduced a regression of #87/#88.

This code should fix it (at least it does for me 👍), unless I'm not understanding something correctly.

### CODE REVIEW

**Comment by jbblanchet** [comment]
I can confirm that this fixes the problem we had with version 5.5.

**Comment by semanser** [comment]
This solution works perfect for me.

**Comment by jbblanchet** [comment]
I started by only implementing the tests for your PR, but while implementing the tests I discovered that we shouldn't always re-bind, because react.createClass is taking care of it, so I updated the code to check how the component was created. Sorry to steal your PR :sweat:

**Comment by Pomax** [comment]
Does this reintroduce the whole "React complaining about `bind()` calls"?

**Comment by RichGuk** [comment]
@jbblanchet  That's fine, I didn't test with createClass.

@Pomax I did wonder that. Which commit actually fixed that?  9d412ca5f832ff813faf0b427a2942400941633d ? Few merges/reverts, was confusing.

**Comment by Pomax** [comment]
Eh, I'll be honest - if this fixes a real bug, then reintroducing a warning is fine. But, if you'd like to help figure out how to now *remove* that warning again, that'd be fantastic.

**Comment by Pomax** [comment]
v5.6.0 just got released after merging in @jbblanchet's PR, does that solve the problem this PR also tried to solve?

**Comment by RichGuk** [comment]
It does thank you @Pomax and @jbblanchet  :)

**Pull request closed without merging**
